### ISSUE TITLE
"I am available from" date dropdown doesn't work in safari

### ISSUE THREAD

**Issue by andyz02** [helping-health/match4healthcare#93]

**Comment by maltezacharias** [comment]
Zu prüfen: Ist das ein Artefakt? Kann das bitte noch wer am Staging Branch ausprobieren?
Student Onboarding Form "Verfügbar ab" sollte eine Datumsauswahl haben, bei @andyz02 vorhin nicht zu sehen. 

Pls tag someone der auf Apple arbeitet

**Comment by josauder** [comment]
https://stackoverflow.com/questions/35682138/html5-date-picker-doesnt-show-on-safari

`<input type="date">` is rendered as a datepicker on every modern browser except Safari.

For Safari we would need to explicitly incude a JS library of somesort for a Datepicker. 

IMO not vital for initial release. We could instead fill the availability start date with "today", as then only those with specific needs need to make changes. Your thoughts?

**Comment by andyz02** [comment]
Würd ich auf alle Fälle auch schon direkt integrieren zum initial release. Das ist wirklich wichtig. Ich kann es mir dann anschauen :)

Liebe Grüße,
Andreas Zehetner

**Comment by feeds** [comment]
I filled it with the today value already in some other branch. Fixes this for now, removing dav-tag

**Comment by maltezacharias** [comment]
Closed, default today is a good enough solution
